name: iamunizen
favicon: null
layout_spectrum: 0.7782111428678036
typography_spectrum: 0.15580810070969164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.42324381531216204
  lightness: 0.934437352232635
  saturation: 0.9431184662971646
  rhythmicContrast: 0.6247476772405207
purpose: []
